credentials:
  usernames:
    quangpham:
      email: quangpham@phs.vn
      name: Pham Minh Quang
      password: $2b$12$/vyhzIE6qBQsYUfW2LVnqefvfZ2V/aO9pSCHjLLtdZP91F4/BSQJe
    haole:
      email: haole@phs.vn
      name: Le Ngoc Anh Hao
      password: $2b$12$ciKPP7pndgdbjCRVGqkmC.yZDakMF/8oYIT3c2EDtAJCIKXgJdScK

cookie:
  expiry_days: 365
  key: random_signature_key # Must be string
  name: random_cookie_name
preauthorized:
  emails:
  - me@mail.com
